import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Edit3, PackagePlus, Percent, Search, Settings2, Tag, Truck, Wrench } from 'lucide-react';
import api from '../api';
import { Button, Card, Field, Input, Loading, Modal, PageHeader, Select } from '../components/UI';
import Status from '../components/Status';
import { CatalogItem, PricingRule } from '../types';
import { currency, shortDate, shortTime } from '../utils';

const blankItem={category:'Windows',product_type:'Sliding',name:'',subtitle:'',profile:'VEKA 60 mm',track:'2 Track',glass:'5 MM Saint Gobain',hardware:'McCoy Hardware',color:'White',min_billable_sft:5,rate_per_sft:0,status:'Active'};

export default function Catalog(){
 const [items,setItems]=useState<CatalogItem[]>([]); const [rules,setRules]=useState<PricingRule|null>(null); const [loading,setLoading]=useState(true); const [search,setSearch]=useState(''); const [category,setCategory]=useState(''); const [tab,setTab]=useState('Categories');
 const [itemOpen,setItemOpen]=useState(false); const [rulesOpen,setRulesOpen]=useState(false); const [editing,setEditing]=useState<CatalogItem|null>(null); const [form,setForm]=useState(blankItem);
 const load=async()=>{setLoading(true);const [a,b]=await Promise.all([api.get('/catalog'),api.get('/pricing-rules')]);setItems(a.data);setRules(b.data);setLoading(false)}; useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>items.filter(i=>(!category||i.category===category)&&`${i.name} ${i.profile} ${i.glass}`.toLowerCase().includes(search.toLowerCase())),[items,search,category]);
 const showAdd=()=>{setEditing(null);setForm(blankItem);setItemOpen(true)};
 const showEdit=(i:CatalogItem)=>{setEditing(i);setForm({category:i.category,product_type:i.product_type,name:i.name,subtitle:i.subtitle,profile:i.profile,track:i.track,glass:i.glass,hardware:i.hardware,color:i.color,min_billable_sft:Number(i.min_billable_sft),rate_per_sft:Number(i.rate_per_sft),status:i.status});setItemOpen(true)};
 const saveItem=async(e:FormEvent)=>{e.preventDefault();if(editing)await api.put(`/catalog/${editing.id}`,form);else await api.post('/catalog',form);setItemOpen(false);await load()};
 const saveRules=async(e:FormEvent)=>{e.preventDefault();if(!rules)return;await api.put('/pricing-rules',rules);setRulesOpen(false);await load()};
 return <>
  <PageHeader title="Catalog & Price Master" subtitle="Manage product catalog, materials and pricing"/>
  <div className="catalog-layout">
   <Card className="catalog-main">
    <div className="tabs">{['Categories','Styles','Materials','Rates','Taxes'].map(x=><button key={x} className={`tab ${tab===x?'active':''}`} onClick={()=>setTab(x)}>{x}</button>)}</div>
    <div className="catalog-filters">
      <Field label="Category"><Select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All Categories</option>{Array.from(new Set(items.map(i=>i.category))).map(c=><option key={c}>{c}</option>)}</Select></Field>
      <Field label="Product Type"><Select><option>All Types</option><option>Sliding</option><option>Casement</option><option>Fixed</option></Select></Field>
      <Field label="Status"><Select><option>Active</option><option>Inactive</option></Select></Field>
      <div className="search-box"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search items..."/></div>
      <Button onClick={showAdd}><PackagePlus size={16}/> Add Item</Button>
    </div>
    {loading?<Loading/>:<div className="table-wrap"><table className="data-table"><thead><tr><th>Category / Product</th><th>Profile</th><th>Track</th><th>Glass</th><th>Hardware</th><th>Color</th><th>Min Billable SFT</th><th>Rate / SFT</th><th>Last Updated</th><th>Status</th><th>Action</th></tr></thead><tbody>{filtered.map(i=><tr key={i.id}><td><div className="product-cell"><div className="product-image"><i/><i/><i/></div><div><span className="cell-title">{i.name}</span><span className="cell-sub">{i.subtitle}</span></div></div></td><td><span className="material-chip">{i.profile}</span></td><td><span className="material-chip">{i.track}</span></td><td><span className="material-chip green">{i.glass}</span></td><td><span className="material-chip purple">{i.hardware}</span></td><td>{i.color}</td><td>{i.min_billable_sft} SFT</td><td className="amount success"><b>{currency(i.rate_per_sft)}</b></td><td>{shortDate(i.updated_at)}<span className="cell-sub">{shortTime(i.updated_at)}</span></td><td><Status value={i.status}/></td><td><button className="mini-button" onClick={()=>showEdit(i)}><Edit3 size={14}/></button></td></tr>)}</tbody></table></div>}
    <div className="pagination"><span>Showing 1 to {filtered.length} of {filtered.length} items</span><div className="pagination-controls"><button className="page-chip">‹</button><button className="page-chip active">1</button><button className="page-chip">›</button><Select style={{width:95}}><option>20 / page</option></Select></div></div>
   </Card>
   <Card className="pricing-panel"><h3>Pricing Rules & Defaults</h3>{rules&&<>
    <div className="rule-section"><div className="rule-title"><span><Truck size={15}/></span><div><b>Transport Charges</b><small>Applies to all deliveries</small></div></div><div className="rule-line"><span>Within City</span><b>{currency(rules.within_city_transport)}</b></div><div className="rule-line"><span>Beyond City</span><b>{currency(rules.beyond_city_transport)}</b></div></div>
    <div className="rule-section"><div className="rule-title"><span style={{background:'#e9faf3',color:'#0caf74'}}><Settings2 size={15}/></span><div><b>Minimum Square Feet</b><small>Applies to all items</small></div></div><div className="rule-line"><span>Minimum Billable</span><b>{rules.minimum_billable_sft} SFT</b></div><div className="rule-line"><span>Rounding</span><b>{rules.rounding_rule}</b></div></div>
    <div className="rule-section"><div className="rule-title"><span style={{background:'#f3efff',color:'#7c3aed'}}><Percent size={15}/></span><div><b>GST (Tax)</b></div></div><div className="rule-line"><span>GST Rate</span><b>{rules.gst_rate}%</b></div><div className="rule-line"><span>Type</span><b>{rules.tax_type}</b></div></div>
    <div className="rule-section"><div className="rule-title"><span style={{background:'#fff5e6',color:'#e99708'}}><Wrench size={15}/></span><div><b>Installation Charges</b></div></div><div className="rule-line"><span>Standard Installation</span><b>{currency(rules.installation_standard)} / SFT</b></div><div className="rule-line"><span>Above 200 SFT</span><b>{currency(rules.installation_above_200)} / SFT</b></div></div>
    <div className="rule-section"><div className="rule-title"><span style={{background:'#fff0f5',color:'#ec4899'}}><Tag size={15}/></span><div><b>Discount Rules</b></div></div><div className="rule-line"><span>Up to 100 SFT</span><b>{rules.discount_upto_100}%</b></div><div className="rule-line"><span>100 – 300 SFT</span><b>{rules.discount_100_300}%</b></div><div className="rule-line"><span>Above 300 SFT</span><b>{rules.discount_above_300}%</b></div></div>
    <Button tone="secondary" style={{width:'100%',marginTop:10}} onClick={()=>setRulesOpen(true)}><Edit3 size={14}/> Edit Pricing Rules</Button></>}
   </Card>
  </div>
  <Modal open={itemOpen} onClose={()=>setItemOpen(false)} title={editing?'Edit Catalog Item':'Add Catalog Item'} width={760}><form onSubmit={saveItem}><div className="form-grid three"><Field label="Category"><Input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></Field><Field label="Product Type"><Input value={form.product_type} onChange={e=>setForm({...form,product_type:e.target.value})}/></Field><Field label="Name" required><Input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Subtitle"><Input value={form.subtitle} onChange={e=>setForm({...form,subtitle:e.target.value})}/></Field><Field label="Profile"><Input value={form.profile} onChange={e=>setForm({...form,profile:e.target.value})}/></Field><Field label="Track"><Input value={form.track} onChange={e=>setForm({...form,track:e.target.value})}/></Field><Field label="Glass"><Input value={form.glass} onChange={e=>setForm({...form,glass:e.target.value})}/></Field><Field label="Hardware"><Input value={form.hardware} onChange={e=>setForm({...form,hardware:e.target.value})}/></Field><Field label="Color"><Input value={form.color} onChange={e=>setForm({...form,color:e.target.value})}/></Field><Field label="Min Billable SFT"><Input type="number" value={form.min_billable_sft} onChange={e=>setForm({...form,min_billable_sft:Number(e.target.value)})}/></Field><Field label="Rate / SFT"><Input type="number" value={form.rate_per_sft} onChange={e=>setForm({...form,rate_per_sft:Number(e.target.value)})}/></Field><Field label="Status"><Select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Active</option><option>Inactive</option></Select></Field></div><div className="form-actions"><Button type="button" tone="secondary" onClick={()=>setItemOpen(false)}>Cancel</Button><Button type="submit">Save Item</Button></div></form></Modal>
  <Modal open={rulesOpen} onClose={()=>setRulesOpen(false)} title="Edit Pricing Rules" width={760}>{rules&&<form onSubmit={saveRules}><div className="form-grid three">{Object.entries(rules).filter(([k])=>k!=='id').map(([key,val])=><Field key={key} label={key.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}>{['rounding_rule','tax_type'].includes(key)?<Input value={String(val)} onChange={e=>setRules({...rules,[key]:e.target.value})}/>:<Input type="number" step="0.01" value={Number(val)} onChange={e=>setRules({...rules,[key]:Number(e.target.value)})}/>}</Field>)}</div><div className="form-actions"><Button type="button" tone="secondary" onClick={()=>setRulesOpen(false)}>Cancel</Button><Button type="submit">Save Rules</Button></div></form>}</Modal>
 </>;
}
