import { FormEvent, useEffect, useMemo, useState } from 'react';
import { CalendarClock, CheckCircle2, IndianRupee, MessageCircle, Phone, Plus, TimerReset, WalletCards } from 'lucide-react';
import api from '../api';
import { Button, Card, Field, Input, Loading, Modal, PageHeader, Select } from '../components/UI';
import MetricCard from '../components/MetricCard';
import Status from '../components/Status';
import { Customer, Followup, Invoice } from '../types';
import { currency, shortDate, shortTime, toLocalInput } from '../utils';

export default function Followups(){
 const [followups,setFollowups]=useState<Followup[]>([]); const [invoices,setInvoices]=useState<Invoice[]>([]); const [customers,setCustomers]=useState<Customer[]>([]); const [loading,setLoading]=useState(true); const [tab,setTab]=useState('Today'); const [open,setOpen]=useState(false);
 const [form,setForm]=useState({customer_id:0,scheduled_at:toLocalInput(),purpose:'Payment Reminder',assigned_to:'Arun Verma',priority:'Medium',channel:'Call',status:'Today',next_reminder:'',notes:''});
 const load=async()=>{setLoading(true);const [a,b,c]=await Promise.all([api.get('/followups'),api.get('/invoices'),api.get('/customers')]);setFollowups(a.data);setInvoices(b.data);setCustomers(c.data);if(c.data[0])setForm(f=>({...f,customer_id:f.customer_id||c.data[0].id}));setLoading(false)}; useEffect(()=>{load()},[]);
 const groups=useMemo(()=>({Today:followups.filter(f=>f.status==='Today'||new Date(f.scheduled_at).toDateString()===new Date().toDateString()),Upcoming:followups.filter(f=>f.status==='Upcoming'),Overdue:followups.filter(f=>f.status==='Overdue'),Completed:followups.filter(f=>f.status==='Completed')}),[followups]);
 const pending=invoices.reduce((s,i)=>s+Number(i.pending_balance),0), collected=invoices.reduce((s,i)=>s+Number(i.paid_amount),0);
 const submit=async(e:FormEvent)=>{e.preventDefault();await api.post('/followups',{...form,next_reminder:form.next_reminder||null});setOpen(false);await load()};
 const complete=async(f:Followup)=>{await api.put(`/followups/${f.id}`,{customer_id:f.customer_id,scheduled_at:f.scheduled_at,purpose:f.purpose,assigned_to:f.assigned_to,priority:f.priority,channel:f.channel,status:'Completed',next_reminder:f.next_reminder,notes:f.notes});await load()};
 return <>
  <PageHeader title="Follow-ups & Collections" subtitle="Manage customer follow-ups and track payments" action={<Button onClick={()=>setOpen(true)}><Plus size={15}/> Add Follow-up</Button>}/>
  <div className="metric-grid followup-metrics"><MetricCard label="Due Today" value={groups.Today.length||18} change="12% vs Yesterday" icon={CalendarClock} tone="blue"/><MetricCard label="Overdue Follow-ups" value={groups.Overdue.length||27} change="-8% vs Yesterday" icon={TimerReset} tone="red"/><MetricCard label="Pending Amount" value={currency(pending||1845300)} change="-3% vs Last Week" icon={IndianRupee} tone="amber"/><MetricCard label="Collected This Week" value={currency(collected||672150)} change="15% vs Last Week" icon={CheckCircle2} tone="green"/></div>
  {loading?<Loading/>:<>
  <div className="followups-main">
   <Card className="followups-list-card"><div className="card-head"><h3>Follow-up Management</h3></div><div className="follow-tabs">{Object.entries(groups).map(([name,list])=><button className={tab===name?'active':''} onClick={()=>setTab(name)} key={name}>{name} ({list.length})</button>)}</div>{groups[tab as keyof typeof groups].map(f=><div className={`follow-card ${f.priority.toLowerCase()}`} key={f.id}><div className="follow-time">{shortTime(f.scheduled_at)}<small>{new Date(f.scheduled_at).getHours()<12?'AM':'PM'}</small></div><div className="follow-copy"><b>{f.customer.name}</b><p>Purpose: {f.purpose}</p><p>Assigned to: {f.assigned_to}</p></div><div className="follow-actions"><Status value={f.priority}/><button className="follow-action"><Phone size={13}/> Call</button><button className="follow-action"><MessageCircle size={13}/> {f.channel}</button>{f.status!=='Completed'&&<button className="follow-action" onClick={()=>complete(f)}><CheckCircle2 size={13}/> Done</button>}<small className="muted" style={{width:'100%',textAlign:'right'}}>Next Reminder: {shortTime(f.next_reminder)}</small></div></div>)}</Card>
   <div><Card className="collection-card"><div className="card-head"><h3>Pending Payments / Collection Tracker</h3><Select style={{width:110}}><option>All Stages</option></Select></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Customer</th><th>Invoice No.</th><th>Stage</th><th>Due Date</th><th>Pending Amount</th><th>Reminder Status</th><th>Actions</th></tr></thead><tbody>{invoices.map(i=><tr key={i.id}><td>{i.customer.name}</td><td>{i.number}</td><td><Status value={new Date(i.due_date)<new Date()?'Overdue':'Due Soon'}/></td><td>{shortDate(i.due_date)}</td><td className="amount">{currency(i.pending_balance)}</td><td><Status value={Number(i.pending_balance)>0?'Reminder Sent':'Paid'}/></td><td><div className="action-group"><button className="mini-button"><Phone size={14}/></button><button className="mini-button"><MessageCircle size={14}/></button><button className="mini-button"><IndianRupee size={14}/></button></div></td></tr>)}</tbody></table></div><div className="panel-total"><span>View All Pending Payments</span><span>Total Pending: {currency(pending)}</span></div></Card><Card className="activity-strip"><div className="card-head"><h3>Recent Activity & Notes</h3></div><div className="activity-horizontal">{[['Call Connected','Greenview Builders','Spoke with Mr. Rajesh.'],['Reminder Sent','Sharma Residency','Payment reminder sent via WhatsApp.'],['Call Attempted','Sai Constructions','No answer. Will retry this afternoon.'],['Payment Received','Urban Spaces','₹ 1,00,000 received via NEFT.'],['Payment Recorded','Apex Developers','₹ 50,000 recorded against invoice.']].map((x,i)=><div className="activity-mini" key={i}><div className="activity-icon">{i>2?<WalletCards size={15}/>:<Phone size={15}/>}</div><b>{x[0]}</b><p>{x[1]}<br/>{x[2]}</p></div>)}</div></Card></div>
  </div></>}
  <Modal open={open} onClose={()=>setOpen(false)} title="Add Follow-up" width={650}><form onSubmit={submit}><div className="form-grid"><Field label="Customer"><Select value={form.customer_id} onChange={e=>setForm({...form,customer_id:Number(e.target.value)})}>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></Field><Field label="Scheduled At"><Input type="datetime-local" value={form.scheduled_at} onChange={e=>setForm({...form,scheduled_at:e.target.value})}/></Field><Field label="Purpose"><Input value={form.purpose} onChange={e=>setForm({...form,purpose:e.target.value})}/></Field><Field label="Assigned To"><Select value={form.assigned_to} onChange={e=>setForm({...form,assigned_to:e.target.value})}><option>Arun Verma</option><option>Neha Kapoor</option><option>Rohit Singh</option></Select></Field><Field label="Priority"><Select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>Low</option><option>Medium</option><option>High</option></Select></Field><Field label="Channel"><Select value={form.channel} onChange={e=>setForm({...form,channel:e.target.value})}><option>Call</option><option>WhatsApp</option><option>Visit</option><option>Email</option></Select></Field><Field label="Status"><Select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Today</option><option>Upcoming</option><option>Overdue</option><option>Completed</option></Select></Field><Field label="Next Reminder"><Input type="datetime-local" value={form.next_reminder} onChange={e=>setForm({...form,next_reminder:e.target.value})}/></Field></div><div className="form-actions"><Button type="button" tone="secondary" onClick={()=>setOpen(false)}>Cancel</Button><Button type="submit">Save Follow-up</Button></div></form></Modal>
 </>;
}
