import { useEffect, useState } from 'react';
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { FileText, IndianRupee, ReceiptText, WalletCards } from 'lucide-react';
import api from '../api';
import { Card, Loading, PageHeader } from '../components/UI';
import MetricCard from '../components/MetricCard';
import { currency } from '../utils';

type Report={total_quote_value:number,total_invoice_value:number,received:number,pending:number,customer_status:Array<{name:string,value:number}>};
export default function Reports(){const [data,setData]=useState<Report|null>(null);useEffect(()=>{api.get('/reports').then(r=>setData(r.data))},[]);if(!data)return <Loading/>;const bars=[{name:'Quotation Value',value:data.total_quote_value},{name:'Invoice Value',value:data.total_invoice_value},{name:'Received',value:data.received},{name:'Pending',value:data.pending}];return <><PageHeader title="Reports" subtitle="Sales, quotation, invoice and collection performance"/><div className="report-grid"><MetricCard label="Total Quote Value" value={currency(data.total_quote_value)} icon={FileText} tone="blue" change="12% this month"/><MetricCard label="Total Invoice Value" value={currency(data.total_invoice_value)} icon={ReceiptText} tone="teal" change="10% this month"/><MetricCard label="Payments Received" value={currency(data.received)} icon={IndianRupee} tone="green" change="15% this month"/><MetricCard label="Pending Collections" value={currency(data.pending)} icon={WalletCards} tone="red" change="-4% this month"/></div><div className="report-charts"><Card className="chart-card"><div className="chart-title"><h3>Financial Overview</h3></div><ResponsiveContainer width="100%" height={300}><BarChart data={bars} margin={{top:10,right:20,left:0,bottom:0}}><CartesianGrid stroke="#edf1f5" vertical={false}/><XAxis dataKey="name" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip formatter={(v)=>currency(Number(v))}/><Bar dataKey="value" fill="#3478f6" radius={[5,5,0,0]} barSize={48}/></BarChart></ResponsiveContainer></Card><Card className="chart-card"><div className="chart-title"><h3>Customer Status</h3></div><ResponsiveContainer width="100%" height={300}><PieChart><Pie data={data.customer_status} dataKey="value" nameKey="name" innerRadius={65} outerRadius={105}>{data.customer_status.map((_,i)=><Cell key={i} fill={['#18b7a4','#3478f6','#f59e0b','#ef4444','#8b5cf6'][i%5]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></Card></div></>}
