import { Route, Routes } from 'react-router-dom';
import { ToastProvider } from './contexts/ToastContext';
import { ConfirmProvider } from './contexts/ConfirmContext';
import Layout from './components/Layout';
import Dashboard from './pages/Dashboard';
import Customers from './pages/Customers';
import Quotations from './pages/Quotations';
import CreateQuotation from './pages/CreateQuotation';
import QuotationDetails from './pages/QuotationDetails';
import Invoices from './pages/Invoices';
import InvoiceDetails from './pages/InvoiceDetails';
import CreditNotes from './pages/CreditNotes';
import CreditNoteDetails from './pages/CreditNoteDetails';
import DebitNotes from './pages/DebitNotes';
import DebitNoteDetails from './pages/DebitNoteDetails';
import Vendors from './pages/Vendors';
import BankAccounts from './pages/BankAccounts';
import PurchaseBills from './pages/PurchaseBills';
import CreatePurchaseBill from './pages/CreatePurchaseBill';
import PurchaseBillDetails from './pages/PurchaseBillDetails';
import Expenses from './pages/Expenses';
import StockItems from './pages/StockItems';
import StockItemDetails from './pages/StockItemDetails';
import FixedAssets from './pages/FixedAssets';
import FixedAssetDetails from './pages/FixedAssetDetails';
import ChartOfAccounts from './pages/ChartOfAccounts';
import AccountLedger from './pages/AccountLedger';
import Journal from './pages/Journal';
import ManualJournalEntry from './pages/ManualJournalEntry';
import JournalEntryDetails from './pages/JournalEntryDetails';
import TrialBalance from './pages/TrialBalance';
import FinancialYears from './pages/FinancialYears';
import GstReports from './pages/GstReports';
import ProfitAndLoss from './pages/ProfitAndLoss';
import BalanceSheet from './pages/BalanceSheet';
import CashFlow from './pages/CashFlow';
import APAging from './pages/APAging';
import TallyExport from './pages/TallyExport';
import Backup from './pages/Backup';
import OpeningBalances from './pages/OpeningBalances';
import Payments from './pages/Payments';
import Followups from './pages/Followups';
import Catalog from './pages/Catalog';
import Reports from './pages/Reports';
import SettingsPage from './pages/SettingsPage';
import NotFound from './pages/NotFound';

export default function App(){return <ToastProvider><ConfirmProvider><Routes><Route element={<Layout/>}><Route path="/" element={<Dashboard/>}/><Route path="/customers" element={<Customers/>}/><Route path="/quotations" element={<Quotations/>}/><Route path="/quotations/new" element={<CreateQuotation/>}/><Route path="/quotations/:id/edit" element={<CreateQuotation/>}/><Route path="/quotations/:id" element={<QuotationDetails/>}/><Route path="/invoices" element={<Invoices/>}/><Route path="/invoices/:id" element={<InvoiceDetails/>}/><Route path="/credit-notes" element={<CreditNotes/>}/><Route path="/credit-notes/:id" element={<CreditNoteDetails/>}/><Route path="/debit-notes" element={<DebitNotes/>}/><Route path="/debit-notes/:id" element={<DebitNoteDetails/>}/><Route path="/vendors" element={<Vendors/>}/><Route path="/bank-accounts" element={<BankAccounts/>}/><Route path="/purchase-bills" element={<PurchaseBills/>}/><Route path="/purchase-bills/new" element={<CreatePurchaseBill/>}/><Route path="/purchase-bills/:id" element={<PurchaseBillDetails/>}/><Route path="/expenses" element={<Expenses/>}/><Route path="/stock-items" element={<StockItems/>}/><Route path="/stock-items/:id" element={<StockItemDetails/>}/><Route path="/fixed-assets" element={<FixedAssets/>}/><Route path="/fixed-assets/:id" element={<FixedAssetDetails/>}/><Route path="/accounts" element={<ChartOfAccounts/>}/><Route path="/accounts/:id" element={<AccountLedger/>}/><Route path="/journal" element={<Journal/>}/><Route path="/journal/new" element={<ManualJournalEntry/>}/><Route path="/journal/:id" element={<JournalEntryDetails/>}/><Route path="/trial-balance" element={<TrialBalance/>}/><Route path="/financial-years" element={<FinancialYears/>}/><Route path="/gst-reports" element={<GstReports/>}/><Route path="/profit-and-loss" element={<ProfitAndLoss/>}/><Route path="/balance-sheet" element={<BalanceSheet/>}/><Route path="/cash-flow" element={<CashFlow/>}/><Route path="/ap-aging" element={<APAging/>}/><Route path="/tally-export" element={<TallyExport/>}/><Route path="/opening-balances" element={<OpeningBalances/>}/><Route path="/backup" element={<Backup/>}/><Route path="/payments" element={<Payments/>}/><Route path="/followups" element={<Followups/>}/><Route path="/catalog" element={<Catalog/>}/><Route path="/reports" element={<Reports/>}/><Route path="/settings" element={<SettingsPage/>}/><Route path="*" element={<NotFound/>}/></Route></Routes></ConfirmProvider></ToastProvider>}
